"""FastAPI scaffold for the LLMO / AI Visibility Platform analysis engine.

This mirrors the shape of the TypeScript `AnalysisResult` type
(`app/lib/types.ts`) and the fixed dummy data currently generated by
`app/lib/dummy-data.ts`, so that Next.js's `/api/analyze` route can call
this service directly without any response transformation.

Common Crawl / DataForSEO / database integrations are intentionally
not wired in yet — see docs/05_tasks.md (Phase 4) for what's next.
"""

from typing import Literal

from fastapi import FastAPI
from fastapi.responses import JSONResponse
from pydantic import BaseModel

app = FastAPI(title="LLMO Analysis API")

Trend = Literal["up", "down", "flat"]
Sentiment = Literal["positive", "neutral", "negative"]
Priority = Literal["high", "medium", "low"]


class SentimentBreakdown(BaseModel):
    positive: int
    neutral: int
    negative: int


class BrandSummary(BaseModel):
    brandName: str
    visibilityScore: int
    totalMentions: int
    sentimentBreakdown: SentimentBreakdown
    topPlatforms: list[str]
    summaryText: str


class CooccurrenceKeyword(BaseModel):
    keyword: str
    count: int
    trend: Trend


class ContextAnalysisItem(BaseModel):
    context: str
    description: str
    sentiment: Sentiment
    exampleQuote: str


class AIOverviewComparisonItem(BaseModel):
    platform: str
    mentioned: bool
    rank: int | None
    summary: str


class ImprovementSuggestion(BaseModel):
    title: str
    description: str
    priority: Priority


class AnalysisResult(BaseModel):
    brandName: str
    summary: BrandSummary
    cooccurrenceRanking: list[CooccurrenceKeyword]
    contextAnalysis: list[ContextAnalysisItem]
    aiOverviewComparison: list[AIOverviewComparisonItem]
    improvements: list[ImprovementSuggestion]


class AnalyzeRequest(BaseModel):
    brandName: str | None = None


def build_dummy_analysis(brand_name: str) -> AnalysisResult:
    """Python port of app/lib/dummy-data.ts's buildDummyAnalysis.

    Fixed content for now; will be replaced by real Common Crawl /
    DataForSEO derived analysis in a later phase.
    """
    return AnalysisResult(
        brandName=brand_name,
        summary=BrandSummary(
            brandName=brand_name,
            visibilityScore=62,
            totalMentions=184,
            sentimentBreakdown=SentimentBreakdown(positive=58, neutral=33, negative=9),
            topPlatforms=["ChatGPT", "Perplexity", "Google AI Overview"],
            summaryText=(
                f"{brand_name}は主要なAIチャットサービスにおいて中程度の認知度を持ち、"
                "直近30日間で言及数は増加傾向にあります。"
                "特に比較・レビュー系のプロンプトでの言及が目立ちます。"
            ),
        ),
        cooccurrenceRanking=[
            CooccurrenceKeyword(keyword="料金プラン", count=42, trend="up"),
            CooccurrenceKeyword(keyword="導入事例", count=35, trend="up"),
            CooccurrenceKeyword(keyword="競合比較", count=29, trend="flat"),
            CooccurrenceKeyword(keyword="サポート体制", count=21, trend="down"),
            CooccurrenceKeyword(keyword="API連携", count=18, trend="up"),
            CooccurrenceKeyword(keyword="口コミ・評判", count=14, trend="flat"),
        ],
        contextAnalysis=[
            ContextAnalysisItem(
                context="比較検討フェーズ",
                description="他社製品と並べて紹介されるケースが最も多く、価格と機能面での比較軸で語られています。",
                sentiment="neutral",
                exampleQuote=f"「{brand_name}は他の類似サービスと比べて◯◯という特徴があります」",
            ),
            ContextAnalysisItem(
                context="導入・活用事例",
                description="実際の活用シーンに関する質問への回答で、好意的な文脈での言及が多く見られます。",
                sentiment="positive",
                exampleQuote=f"「{brand_name}を使うことで業務効率が向上したという事例があります」",
            ),
            ContextAnalysisItem(
                context="サポート・不満点",
                description="サポート対応の遅さや学習コストについて言及される文脈で、やや否定的な評価も見られます。",
                sentiment="negative",
                exampleQuote=f"「{brand_name}はサポート対応に時間がかかるという意見もあります」",
            ),
        ],
        aiOverviewComparison=[
            AIOverviewComparisonItem(
                platform="Google AI Overview",
                mentioned=True,
                rank=2,
                summary="比較記事からの引用として2番目に表示されることが多い。",
            ),
            AIOverviewComparisonItem(
                platform="ChatGPT",
                mentioned=True,
                rank=1,
                summary="関連する質問に対して第一想起として挙げられる頻度が高い。",
            ),
            AIOverviewComparisonItem(
                platform="Perplexity",
                mentioned=True,
                rank=3,
                summary="情報源として公式サイトとレビューサイトが引用される傾向。",
            ),
            AIOverviewComparisonItem(
                platform="Copilot",
                mentioned=False,
                rank=None,
                summary="現時点では明確な言及が確認されていません。",
            ),
        ],
        improvements=[
            ImprovementSuggestion(
                title="比較コンテンツの拡充",
                description="競合比較の文脈での言及が多いため、公式サイトに詳細な比較表や導入メリットをまとめたページを用意すると引用されやすくなります。",
                priority="high",
            ),
            ImprovementSuggestion(
                title="FAQ・サポート情報の構造化",
                description="サポートに関するネガティブな言及を減らすため、よくある質問と回答をFAQ形式で整理し、AIが引用しやすい構造にすることを推奨します。",
                priority="medium",
            ),
            ImprovementSuggestion(
                title="導入事例ページの強化",
                description="好意的な文脈で引用されやすい導入事例を増やし、具体的な数値や業種別事例を追加すると認知度向上が期待できます。",
                priority="medium",
            ),
            ImprovementSuggestion(
                title="Copilotでの露出強化",
                description="Copilotでの言及がまだ少ないため、Bing/Microsoft系のインデックスに載りやすいコンテンツ配信を検討してください。",
                priority="low",
            ),
        ],
    )


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


@app.post("/analyze", response_model=AnalysisResult)
def analyze(payload: AnalyzeRequest):
    brand_name = (payload.brandName or "").strip()
    if not brand_name:
        return JSONResponse(status_code=400, content={"error": "brandName is required"})

    return build_dummy_analysis(brand_name)
